### Requisição para a raiz da aplicação
GET http://localhost:3000

### Requisição passando parametros na URL
GET http://localhost:3000/12/arroz

### Requiisição passando informação pelo corpo da requisição
POST http://localhost:3000
Content-Type: application/json

{
   
    "nome" : "Amendoim",
    "preco" : 10

}